### ISSUE TITLE
Feature Request: Generate image if none available

### ISSUE THREAD

**Issue by heliostatic** [RadhiFadlillah/shiori#24]
When adding or updating a bookmark, Shiori currently grabs the image url from the meta tags of the site (https://github.com/RadhiFadlillah/shiori/blob/master/cmd/add.go#L71).

However, if a site doesn't have an image, none is assigned.

Ideally, if no image is available, Shiori could generate one using PhantomJS or Chrome Headless. One Golang project to do so is [Gowitness](https://github.com/sensepost/gowitness) (go + chrome headless).

**Comment by RadhiFadlillah** [comment]
Hi @heliostatic

I've been considering adding that feature before. However, I dropped it because it requires additional dependencies like Chrome, which I think overkill just to fetch the screenshot.

I will consider to use favicon as alternative if featured image doesn't exist. It's far easier and doesn't requires any dependencies. Besides favicon nowadays is quite large thanks to Apple spec.

I will move this issue to [RadhiFadlillah/go-readability#5](https://github.com/RadhiFadlillah/go-readability/issues/5).
