### ISSUE TITLE
Feature Request: Strip UTM params from URLs (optionally?)

### ISSUE THREAD

**Issue by heliostatic** [RadhiFadlillah/shiori#26]
When adding a bookmark, add an option to strip UTM parameters.

Last feature request for now, I promise!

**Comment by RadhiFadlillah** [comment]
Hey, I think it should be easy enough to do. You can expect this feature to be added on this or next week. 

However, should `shiori` strips UTM parameter by default or if only specified by user ?

**Comment by heliostatic** [comment]
I think strip by default. Most of the time of the time users won't care about preserving marketing data.

**Comment by RadhiFadlillah** [comment]
Done in [d167379](https://github.com/RadhiFadlillah/shiori/commit/d16737954621485f93c0597794792be67adf2244).

After thinking about it, I make the UTM parameters will always be removed, because those parameter is useless for the reader. So, I don't think there are any need to add flag for keeping the UTMs.
