### ISSUE TITLE
Delete fails from web interface

### ISSUE THREAD

**Issue by csterritt** [RadhiFadlillah/shiori#32]
I created several test links with the web front end, and tried deleting one.  I got an error message, "no token present in request".

**Comment by RadhiFadlillah** [comment]
Hi @csterritt, sorry for late response.

So, while using the web interface, you succeed on adding several new bookmarks, but failed when deleting one of them ?

>  I got an error message, "no token present in request".

That message means that user session already ended, which makes the token expired and you have to login again. Do you delete the bookmark right after adding it, or several hours after adding it ?

Thanks.

**Comment by csterritt** [comment]
Hi @RadhiFadlillah -- it was pretty much immediate, within a minute.

**Comment by RadhiFadlillah** [comment]
@csterritt sorry for late response.

After checking around, I don't think this issue is a bug. The error message `no token present` means the user session already ended, so user have to login again, and this is the intended behaviour.

For now I've added better error message for clarity, and redirected user to login page when token expired (commit [`4deed23`](https://github.com/RadhiFadlillah/shiori/commit/4deed23fd45f10566968a6debf9e4fa5c6343258)).
