### ISSUE TITLE
Add a Windows build in the releases

### ISSUE THREAD

**Issue by x2764tech** [RadhiFadlillah/shiori#5]
This looks like a great project, but it would be really useful to run this on Windows (I can use a wrapper to either run it as a service or on login)

Would it be possible to add a Windows build in the releases?

**Comment by RadhiFadlillah** [comment]
Yes, it's possible since Go make cross compile really easy. However, right now I don't have any access to Windows PC since I'm using Linux as main workstation, so I will do it later I guess.

**Comment by arendtio** [comment]
Well, I stumbled upon this one and thought: "That should be a no brainer" and started

`env GOOS=windows GOARCH=386 go get github.com/RadhiFadlillah/shiori`

And in fact it resulted in a shiori.exe which I transfered to a windows machine and started it:

`go-sqlite3 requires cgo to work`

So it ain't that easy, because go-sqlite requires some C library which is not go code and therefore not that easy to cross compile. If someone wants to try it at a later point, I came across that reddit post

https://www.reddit.com/r/golang/comments/3tx2a5/how_do_i_build_a_cross_platform_go_program/

but as I don't want to install `mingw32` right now that is something someone else should check out ;-)

**Comment by intabulas** [comment]
I would suggest something like goreleaser (https://github.com/goreleaser/goreleaser) which will cross compile, upload to github releases and generate homebrew tap for those on OSX

**Comment by DWSR** [comment]
@arendtio Just set `CGO_ENABLED=0`

**Comment by DWSR** [comment]
@arendtio @RadhiFadlillah I was able to successfully build this for Windows under WSL. I have added the instructions to the README via #68 in the hopes that it can help provide some guidance.

**Comment by Shadesss** [comment]
Would love shiori for windows!

**Comment by RadhiFadlillah** [comment]
Since the Windows binary has been available in [v1.0](https://github.com/RadhiFadlillah/shiori/releases/tag/v1.0), I will close this issue for now.
