### ISSUE TITLE
Show update status on console

### ISSUE THREAD

**Issue by muesli** [RadhiFadlillah/shiori#69]
Updating all bookmarks from the console with `shiori update -y` can take some time if you've stored hundreds or thousands of them. Currently shiori seems to update them all and only then prints out the results to the screen.

It would be nice if it could continuously update the progress. Maybe even display a nice little progress bar? Checkout https://github.com/muesli/goprogressbar for some inspiration.

**Comment by RadhiFadlillah** [comment]
Hi @muesli, I've added progress bar while fetching new content in commit [5b36d4](https://github.com/RadhiFadlillah/shiori/commit/5b36d4500f2904690099d71297df4975ce224f4b).

BTW I also fix the slow update process in commit [9d025dc](https://github.com/RadhiFadlillah/shiori/commit/9d025dc6a2f5dc3b8f347c46d503e77207123b7d). This problem is happened because I forgot to put update queries inside the transaction. Now the update should be a lot faster than before.

**Comment by muesli** [comment]
Looks nice!
