### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by BoundsCheck** [RadhiFadlillah/shiori#73]
Any chance for a dark theme being included ? Or (ideally I suppose) some way to define your own.

**Comment by gissehel** [comment]
This is *not* a valid answer to the request, but it *may* be an answer that would please people wondering for a dark theme, if they don't know such thing exists.

There is a navigator extension (stylish) that let's you create/share/install new style (in the sens of a css style) for web sites.

As a proof of concept, I created a dark style for shori: https://userstyles.org/styles/158511/shiori-dark-theme (Note/disclaimer: As I don't use dark styles, I don't intend to maintain that style when shiori will evoluate).

You can install stylish for your browser (Chrome/Baidu/Firefox/Opera officially supported), and then install that style (but just clicking on the install link on the style page).

it will work on any site with "shiori" insidide the domain name (eg: https://shiori.example.com/). If you host your shiori on anything else (like https://bookmark-manager.example.com/ or http://127.0.0.1:8080/) you'll need to go to your stylish installed styles and add your domain to style.

and because everyone loves screenshots, here is the comparison without and with the theme:

![shiori-default-theme](https://user-images.githubusercontent.com/199364/38777446-846d5f4a-40a8-11e8-82df-7ab34da342f0.png)

![shiori-dark-theme](https://user-images.githubusercontent.com/199364/38777445-8452ef2a-40a8-11e8-99e3-778f1e94d1a7.png)

**Comment by gissehel** [comment]
I submitted a PR #85 in order to provide a dark theme, but it only contains CSS part. It needs some code (that would only have to add/change the class on the body element to put "theme-dark" or "theme-light").

**Comment by RadhiFadlillah** [comment]
Hi @gissehel @BoundsCheck, I've implemented the night theme in the last commit :

![screen shot 2018-05-25 at 13 12 42](https://user-images.githubusercontent.com/6129042/40529763-7452f2cc-6020-11e8-9e61-f31908dde460.png)

If you want to update your shiori, do note there are change in environment variables, so if you want to update it, you might have to move your database file to new location.
