### ISSUE TITLE
Feature request : Add a bookmarklet to add a page to shiori directly by cliking on a bookmarklet on a given page.

### ISSUE THREAD

**Issue by gissehel** [RadhiFadlillah/shiori#84]
Add a bookmarklet to add a page to shiori directly by cliking on a bookmarklet on a given page.

Expected usage
==========

* On the shiori main page, there would be a link named "Add" or "Add to shiori" that would link to an addresse like `javascript:(function(){...})()`
* By drag & dropping the link the bookmark bar, the user would "install" the bookmarklet
* When browsing a web site (eg: www.google.com), the user would click on the link "Add to shiori" that would then execute the javascript contained in the link.
* The javascript would then insert the current page into the shiori server, using the currently logged user,  with no title and no tag (or with a #to_sort tag)

**Comment by RadhiFadlillah** [comment]
Hi guys, sorry for late response.

I've made a simple bookmarklet for `shiori` that works by sending POST request to `$SHIORI/api/bookmarks` through `XMLHttpRequest`. The problem is this only works if `$SHIORI` is HTTPs, because the modern web browser now blocks all [active mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).

Now, since `shiori` is self hosted, not all user can serve it behind HTTPs. To solve it, as the fallback when `$SHIORI` is not HTTPs, I'm planning to make the bookmarklet redirects user to submit page `$SHIORI/submit?url=...` (just like [Reddit's submit page](https://www.reddit.com/submit)).

If all goes well this feature should be committed on these following days.

**Comment by 5hay** [comment]
Since you can get a SSL certificate pretty easily and for free through LetsEncrypt, you could maybe integrate auto certificate renewal.

https://godoc.org/golang.org/x/crypto/acme/autocert as a reference.

I think most shiori instances are available over the internet, that's why I would definitely recommend a SSL certificate.

**Comment by RadhiFadlillah** [comment]
I've added bookmarklet in commit [`4b93937`](https://github.com/RadhiFadlillah/shiori/commit/4b939379e83b34f6d9d97517a80b8dd44313bbe8). To use it, just drag the `Add new bookmark` button to your bookmark toolbar :

![Screencast](https://user-images.githubusercontent.com/6129042/41046069-e255a74e-69d3-11e8-9723-8fe0f811e168.gif)

When possible (i.e. allowed by CSP), the bookmarklet will show dialog for saving new bookmark :

![As dialog](https://user-images.githubusercontent.com/6129042/41046287-5c5a5774-69d4-11e8-8459-bf7a71297e47.png)

However, if it's not possible, the bookmarklet will redirect you to submit page :

![As submit page](https://user-images.githubusercontent.com/6129042/41046461-a60c8ac2-69d4-11e8-84af-245a070180f1.png)

Please try it out.

---

> Since you can get a SSL certificate pretty easily and for free through LetsEncrypt, you could maybe integrate auto certificate renewal...

I don't think I will do it, because :

- It adds new complexity to `shiori`. Right now I just want to focus on making shiori stable and reliable enough to use.
- When user self hosted `shiori`, they usually put it behind a web server anyway, and there are already many good web server that can fetch SSL certificate from Let'sEncrypt, e.g Caddy and nginx.

**Comment by 5hay** [comment]
Works pretty nice, running behind a Nginx reverse proxy on my Raspberry Pi via Docker. Thank you!

**Comment by gissehel** [comment]
As it works fine, I'll close the issue.

**Comment by mzch** [comment]
Hi,

Bookmarklet can’t  be drag to toolbar on Chrome 74.0.3729.108 or later and Safari 12.1.
Is this only my own problem?

**Comment by imjoeyli** [comment]
It doesn't work now? The add button can't drag and drop.

**Comment by jajpater** [comment]
Doesn't work here either

**Comment by 8bitgentleman** [comment]
The bookmarklet has been depreciated and the official method is now the [web extension](https://github.com/go-shiori/shiori-web-ext)

**Comment by jajpater** [comment]
@8bitgentleman I know, but that didn't work for me either [see this issue](https://github.com/go-shiori/shiori-web-ext/issues/18)
