### ISSUE TITLE
Anchors in URLs get encoded incorrectly

### ISSUE THREAD

**Issue by muesli** [RadhiFadlillah/shiori#91]
When storing a URL with an anchor (e.g. https://foo#bar) the hash character gets encoded incorrectly as `%23`.

**Comment by RadhiFadlillah** [comment]
@muesli thanks for the report. This happened because `url.ParseRequestURI` (which used for validating URL) always assume that the raw URL string doesn't have any `#fragment` suffix.

To fix this, I've reverted `ParseRequestURI` to normal `Parse` in [`1baf921`](https://github.com/RadhiFadlillah/shiori/commit/1baf921b491db8b1a2218c81cf32471bdd2d3fcd). I've also removed the fragment from URL in [`7532d36`](https://github.com/RadhiFadlillah/shiori/commit/7532d36e7e61ff60395f1819bd9010d7b723074e) because AFAIK the anchor tag (#) is only used by web browser, and not by web server.

**Comment by RadhiFadlillah** [comment]
Hi @muesli, I’m closing this issue for now because :

- It has been fixed, and;
- It has been inactive for a while, so I guess this issue has been solved. 

Feels free to reopen it if needed.

Thank you.

**Comment by mailinglists35** [comment]
this is not fixed. i still cannot add url with anchor. using latest release binary. if it is fixed in master, perhaps could you try make a new release or at least a snapshot of the current master?

**Comment by mailinglists35** [comment]
i mean... i really want to store an url containing a fragment.... :) the fix was to remove support for fragments altogether :-(
