### ISSUE TITLE
Question: How to disable cache?

### ISSUE THREAD

**Issue by yasuokav** [RadhiFadlillah/shiori#92]
> Where possible, by default shiori will download a static copy of the webpage in simple text and HTML format, which later can be used as an offline archive for that page.

But how to disable this feature?

**Comment by RadhiFadlillah** [comment]
If you use command line interface, you can use `--offline` flag in `add` and `update` command. However, if you use the web interface, there are no way to disable caching while adding the new bookmark. 

The main reason I've created `shiori` in the first place is because AFAIK there are no bookmarks manager that also save the archive of a webpage. So I don't think this feature will be added any time soon.

**Comment by yasuokav** [comment]
@RadhiFadlillah Thanks for your answer!
