### ISSUE TITLE
configuration is stored session based. I would expect it to be stored on server user based

### ISSUE THREAD

**Issue by gissehel** [RadhiFadlillah/shiori#98]
Steps to reproduce
---------------------

- Open a shiori site
- Change the configuration
- Logout
- Open the same site on another computer/web browser

Expected results
------------------

- The configuration is the same as last one on the first computer

Actuel results
---------------

- The configuration is the default configuration

Informations
========

- Used threw docker latest official image to date ( imageid: aa87bff95d6e )

**Comment by RadhiFadlillah** [comment]
I'm not sure I want to do this. The reasons are :

- We need to add new table and new API endpoint for managing configuration.
- When the index page loaded, it need to fetch the configuration from the API. Right now, when it finished loading, the index page already fetch data from two endpoint, i.e. `/api/bookmarks` and `/api/tags`. I'm worried that if we add another one, it will make the load time too long.
- It adds new complexity while the result is not too significant. I mean, this feature will be useful if there are lots options to configure. However, right now `shiori` only have three options, and all those options is only for the appearance.

Beside the above reasons, I rather like the current method where the config is saved locally in the device. It fast to load, fast to change, and I can set different options for different device. 

For example, when using my PC, I prefer to use `shiori` in light mode and list mode. However, when using my phone, since I only use it at night after finished working, I prefer to use the night mode and grid mode.

**Comment by gissehel** [comment]
I'm using 5 different computers on a daily basis, which is why I like to have a central repository for my bookmarks, and shiori is fine for that.

The argument about diffence between list/grid on different devices make sense, so the best solution would be to be able to choose between global (user based) configuration and local (session based) configuration for each configuration item. 

But that would start to make a messy configuration messagebox. So I'll close the issue for now.
